def compute_confidence_score(style_score: float, llm_score: float, lexical_score: float) -> tuple:
    """
    Ensemble combiner for three independent detection signals into a single
    ai_probability and a confidence (signal-agreement) value.

    Weighting strategy (planning.md, updated for the 3-signal ensemble):
        ai_probability = 0.30 * style_score + 0.50 * llm_score + 0.20 * lexical_score

    Weights are assigned by how much signal each source captures on its own:
    the LLM classifier gets the largest share (0.50) because it reasons about
    higher-level semantic patterns; stylometric heuristics get the next share
    (0.30) as a solid structural signal; lexical diversity gets the smallest
    share (0.20) because type-token ratio and word-length uniformity are the
    noisiest of the three, especially on short text, so it acts as a
    tie-breaking nudge rather than a primary vote.

    Conflict resolution: confidence measures how tightly the three signals
    agree, generalizing the original |style - llm| formula to three signals
    via the range (max - min) across all of them:
        confidence = 1.0 - (max(scores) - min(scores))
    A wide spread between any two signals drags confidence down and (via the
    existing threshold table) forces the label to "uncertain" -- no single
    signal can out-vote a disagreement, which is intentional: the ensemble
    is designed to admit uncertainty rather than force a false consensus.
    """
    scores = (style_score, llm_score, lexical_score)
    ai_probability = round(0.30 * style_score + 0.50 * llm_score + 0.20 * lexical_score, 4)
    confidence = round(1.0 - (max(scores) - min(scores)), 4)
    return ai_probability, confidence


def generate_label(ai_probability: float, confidence: float) -> tuple:
    """
    Maps (ai_probability, confidence) to a label variant + exact label text.

    Threshold table (planning.md):
        confidence < 0.70                                  -> uncertain
        confidence >= 0.70 AND ai_probability > 0.55        -> ai_high
        confidence >= 0.70 AND ai_probability <= 0.55       -> human_high
    """
    pct = round(ai_probability * 100)

    if confidence < 0.70:
        label_variant = "uncertain"
        label_text = (
            f"We couldn't confidently determine whether this content is "
            f"human-written or AI-generated (AI probability: {pct}%). "
            f"Our signals gave mixed results. If you wrote this yourself, "
            f"you can file an appeal below."
        )
    elif ai_probability > 0.55:
        label_variant = "ai_high"
        label_text = (
            f"Our analysis suggests this content was likely generated by AI "
            f"(AI probability: {pct}%). We detected consistent patterns "
            f"associated with AI writing across multiple signals."
        )
    else:
        label_variant = "human_high"
        label_text = (
            f"Our analysis suggests this content was likely written by a "
            f"human (AI probability: {pct}%). Multiple signals found "
            f"characteristics consistent with human authorship."
        )

    return label_variant, label_text