BASE_WEIGHTS = {"style": 0.30, "llm": 0.50, "lexical": 0.20}


def compute_confidence_score(style_score: float, llm_score: float, lexical_score) -> tuple:
    """
    Ensemble combiner for three independent detection signals into a single
    ai_probability and a confidence (signal-agreement) value.

    Weighting strategy (planning.md, updated for the 3-signal ensemble):
        ai_probability = 0.30 * style_score + 0.50 * llm_score + 0.20 * lexical_score

    Weights are assigned by how much signal each source captures on its own:
    the LLM classifier gets the largest share (0.50) because it reasons about
    higher-level semantic patterns; stylometric heuristics get the next share
    (0.30) as a solid structural signal; lexical diversity gets the smallest
    share (0.20) because type-token ratio and word-length uniformity are the
    noisiest of the three, especially on short text, so it acts as a
    tie-breaking nudge rather than a primary vote.

    lexical_score may be None (the signal abstains on short text -- see
    signals/lexical_diversity.py). An abstention is dropped entirely rather
    than treated as a "neutral 0.5" vote: a fabricated neutral score would
    still count as disagreement against two signals that strongly agree,
    systematically pushing the ensemble toward "uncertain" on typical short
    submissions. Abstaining signals are excluded from both the weighted
    average (remaining weights renormalize to sum to 1) and the agreement
    calculation below.

    Conflict resolution: confidence measures how tightly the *voting*
    signals agree, generalizing the original |style - llm| formula to N
    signals via the range (max - min) across whichever signals voted:
        confidence = 1.0 - (max(scores) - min(scores))
    A wide spread between any two signals drags confidence down and (via the
    existing threshold table) forces the label to "uncertain" -- no single
    signal can out-vote a disagreement, which is intentional: the ensemble
    is designed to admit uncertainty rather than force a false consensus.
    """
    candidates = {"style": style_score, "llm": llm_score, "lexical": lexical_score}
    voting = {name: score for name, score in candidates.items() if score is not None}

    weight_total = sum(BASE_WEIGHTS[name] for name in voting)
    ai_probability = round(
        sum(BASE_WEIGHTS[name] * score for name, score in voting.items()) / weight_total, 4
    )

    scores = list(voting.values())
    confidence = round(1.0 - (max(scores) - min(scores)), 4) if len(scores) > 1 else 1.0

    return ai_probability, confidence


def generate_label(ai_probability: float, confidence: float) -> tuple:
    """
    Maps (ai_probability, confidence) to a label variant + exact label text.

    Threshold table (planning.md):
        confidence < 0.70                                  -> uncertain
        confidence >= 0.70 AND ai_probability > 0.55        -> ai_high
        confidence >= 0.70 AND ai_probability <= 0.55       -> human_high
    """
    pct = round(ai_probability * 100)

    if confidence < 0.70:
        label_variant = "uncertain"
        label_text = (
            f"We couldn't confidently determine whether this content is "
            f"human-written or AI-generated (AI probability: {pct}%). "
            f"Our signals gave mixed results. If you wrote this yourself, "
            f"you can file an appeal below."
        )
    elif ai_probability > 0.55:
        label_variant = "ai_high"
        label_text = (
            f"Our analysis suggests this content was likely generated by AI "
            f"(AI probability: {pct}%). We detected consistent patterns "
            f"associated with AI writing across multiple signals."
        )
    else:
        label_variant = "human_high"
        label_text = (
            f"Our analysis suggests this content was likely written by a "
            f"human (AI probability: {pct}%). Multiple signals found "
            f"characteristics consistent with human authorship."
        )

    return label_variant, label_text