import json
import os
from groq import Groq

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

SYSTEM_PROMPT = """You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the text and return ONLY a JSON object with this exact format:
{"ai_probability": <float between 0.0 and 1.0>}

0.0 = definitely human-written
1.0 = definitely AI-generated

Look for these signals:
- Uniform sentence structure and length (AI tends to be metronomic)
- Overused transitional phrases: "furthermore", "it is worth noting", "in conclusion"
- Hollow specificity: sounds informative but lacks concrete personal detail
- No genuine personal voice, unexpected tangents, or mid-thought corrections
- Overly balanced phrasing: "on one hand... on the other hand"

Return ONLY valid JSON. No explanation, no markdown."""


def classify_with_llm(text: str) -> dict:
    """
    Signal 1 — LLM classifier via Groq.
    Returns {"llm_score": float} where 1.0 = strong AI signal.
    """
    try:
        response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text[:4000]}"},
            ],
            temperature=0.1,
            max_tokens=30,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown fences if model disobeys instructions
        raw = raw.strip("`").strip()
        if raw.startswith("json"):
            raw = raw[4:].strip()
        data = json.loads(raw)
        score = max(0.0, min(1.0, float(data["ai_probability"])))
    except (json.JSONDecodeError, KeyError, ValueError):
        score = 0.5  # neutral fallback so the system still responds

    return {"llm_score": round(score, 4)}
